### ISSUE TITLE
help

### ISSUE THREAD

**Issue by billantony** [salman0ansari/whatsapp-api-nodejs#103]
await WhatsAppInstances[req.query.key].instance?.sock?.logout();
                                                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/www/wwwroot/apiwassap_cobbadental_com/wassapAPI-v3/src/api/routes/instance.route.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-api-nodejs@3.0.0 start: `node src/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the whatsapp-api-nodejs@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by salman0ansari** [comment]
upgrade node to 14+
