### ISSUE TITLE
Memory leak detected

### ISSUE THREAD

**Issue by Zarinia** [salman0ansari/whatsapp-api-nodejs#139]
```
WhatsApp-2  | Jun-09-2022 22:27:54 [server] error: Unhandled Rejection at: Promise
WhatsApp-2  | (node:628) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [File]. Use emitter.setMaxListeners() to increase limit
WhatsApp-2  |     at _addListener (node:events:601:17)
WhatsApp-2  |     at File.addListener (node:events:619:10)
WhatsApp-2  |     at File.once (node:events:663:8)
WhatsApp-2  |     at /usr/src/app/node_modules/winston/lib/winston/rejection-handler.js:220:19
WhatsApp-2  |     at /usr/src/app/node_modules/async/internal/withoutIndex.js:8:40
WhatsApp-2  |     at eachOfArrayLike (/usr/src/app/node_modules/async/eachOf.js:61:9)
WhatsApp-2  |     at eachOf (/usr/src/app/node_modules/async/eachOf.js:181:12)
WhatsApp-2  |     at awaitable (/usr/src/app/node_modules/async/internal/awaitify.js:13:28)
WhatsApp-2  |     at eachLimit (/usr/src/app/node_modules/async/forEach.js:125:31)
```

**Comment by salman0ansari** [comment]
ok

**Comment by salman0ansari** [comment]
learn node.js
