### ISSUE TITLE
this.isZero()

### ISSUE THREAD

**Issue by abhi143u11** [salman0ansari/whatsapp-api-nodejs#23]
If I am using WhatsApp business on iPhone its gives an error from the second message the first message works fine but the second message gives an error like this.isZero() is not a function. 

Its works fine with WhatsApp business android but not with iPhone (tried on iPhone 6s and iPhone 12)

**Comment by salman0ansari** [comment]
Show full error log

**Comment by abhi143u11** [comment]
2022-02-21T14:32:03.547830+00:00 app[web.1]: /app/node_modules/long/src/long.js:474
2022-02-21T14:32:03.547841+00:00 app[web.1]:     if (this.isZero())
2022-02-21T14:32:03.547842+00:00 app[web.1]:              ^
2022-02-21T14:32:03.547843+00:00 app[web.1]: 
2022-02-21T14:32:03.547843+00:00 app[web.1]: TypeError: this.isZero is not a function
2022-02-21T14:32:03.547844+00:00 app[web.1]:     at String.toString (/app/node_modules/long/src/long.js:474:14)
2022-02-21T14:32:03.547844+00:00 app[web.1]:     at Function.toObject (/app/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:22939:113)
2022-02-21T14:32:03.547845+00:00 app[web.1]:     at Function.toObject (/app/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:25861:62)
2022-02-21T14:32:03.547845+00:00 app[web.1]:     at Function.toObject (/app/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:43886:78)
2022-02-21T14:32:03.547845+00:00 app[web.1]:     at Function.toObject (/app/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:41271:54)
2022-02-21T14:32:03.547845+00:00 app[web.1]:     at Function.toObject (/app/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:43938:74)
2022-02-21T14:32:03.547846+00:00 app[web.1]:     at Function.toObject (/app/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:51361:54)
2022-02-21T14:32:03.547846+00:00 app[web.1]:     at WebMessageInfo.toJSON (/app/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:51444:37)
2022-02-21T14:32:03.547847+00:00 app[web.1]:     at JSON.stringify (<anonymous>)
2022-02-21T14:32:03.547847+00:00 app[web.1]:     at stringify (/app/node_modules/express/lib/response.js:1128:12)

**Comment by salman0ansari** [comment]
Strange, never seen this error. 🤔

**Comment by salman0ansari** [comment]
i think your msg.body is invalid JSON

**Comment by abhi143u11** [comment]
even if now I am sending message using api-docs its giving error as follows 


2022-02-22T17:40:59.210736+00:00 app[web.1]: /app/node_modules/long/src/long.js:474
2022-02-22T17:40:59.210749+00:00 app[web.1]:     if (this.isZero())
2022-02-22T17:40:59.210750+00:00 app[web.1]:              ^
2022-02-22T17:40:59.210750+00:00 app[web.1]: 
2022-02-22T17:40:59.210751+00:00 app[web.1]: TypeError: this.isZero is not a function
2022-02-22T17:40:59.210752+00:00 app[web.1]:     at String.toString (/app/node_modules/long/src/long.js:474:14)
2022-02-22T17:40:59.210752+00:00 app[web.1]:     at Function.toObject (/app/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:22939:113)
2022-02-22T17:40:59.210753+00:00 app[web.1]:     at Function.toObject (/app/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:25861:62)
2022-02-22T17:40:59.210753+00:00 app[web.1]:     at Function.toObject (/app/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:43886:78)
2022-02-22T17:40:59.210754+00:00 app[web.1]:     at Function.toObject (/app/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:41271:54)
2022-02-22T17:40:59.210754+00:00 app[web.1]:     at Function.toObject (/app/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:43938:74)
2022-02-22T17:40:59.210754+00:00 app[web.1]:     at Function.toObject (/app/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:51361:54)
2022-02-22T17:40:59.210754+00:00 app[web.1]:     at WebMessageInfo.toJSON (/app/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:51444:37)
2022-02-22T17:40:59.210755+00:00 app[web.1]:     at JSON.stringify (<anonymous>)
2022-02-22T17:40:59.210755+00:00 app[web.1]:     at stringify (/app/node_modules/express/lib/response.js:1128:12)
2022-02-22T17:40:59.336991+00:00 heroku[web.1]: Process exited with status 1
2022-02-22T17:40:59.406587+00:00 heroku[web.1]: State changed from up to crashed

**Comment by salman0ansari** [comment]
what are you sending in body?

**Comment by abhi143u11** [comment]
{
  "msg_data": {
    "id": "91*number",
    "message": "Message"
  }
}

**Comment by abhi143u11** [comment]
today found out that its working fine with android devices but when ever i send a single message to iphone the above error occurs

**Comment by abhi143u11** [comment]
I am posting like this 

        $curl = curl_init();

        curl_setopt_array($curl, array(
            CURLOPT_URL => 'https://www.example.com/sendText?key=apikey',
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => '',
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => 'POST',
            CURLOPT_POSTFIELDS => '{
"msg_data": {
"id": "' . $this->phone . '",
"message": "'.$this->message.'"
}
}',
            CURLOPT_HTTPHEADER => array(
                'Content-Type: application/json'
            ),
        ));

        $response = curl_exec($curl);

**Comment by abhi143u11** [comment]
After few days of testing the above errors occurs only when disappearing messages are turned on. When I turned disappearing off it’s working fine
