### ISSUE TITLE
Error in use github version

### ISSUE THREAD

**Issue by exallhost** [salman0ansari/whatsapp-api-nodejs#274]
After I try to use the git version directly.

When running the api, it shows the following error:

root@send:~/api-whatsapp-dev# npm i github:adiwajshing/baileys
[         .........] - extract:fsevents: sill extract fsevents@2.3.2 extracted to /root/api-whatsapp-dev/node_modules/.staging/fsevents-29660beb (22ms)
[         .........] - extract:fsevents: sill extract fsevents@2.3.2 extracted to /root/api-whatsapp-dev/node_modules/.staging/fsevents-29660beb (22ms)
[         .........] - extract:fsevents: sill extract fsevents@2.3.2 extracted to /root/api-whatsapp-dev/node_modules/.staging/fsevents-29660beb (22ms)
[         .........] - extract:fsevents: sill extract fsevents@2.3.2 extracted to /root/api-whatsapp-dev/node_modules/.staging/fsevents-29660beb (22ms)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @adiwajshing/baileys@4.4.0
updated 1 package and audited 503 packages in 841.74s

92 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
root@send:~/api-whatsapp-dev# 
root@send:~/api-whatsapp-dev# 
root@send:~/api-whatsapp-dev# 
root@send:~/api-whatsapp-dev# 
root@send:~/api-whatsapp-dev# yarn start
yarn run v1.22.19
$ supervisor src/server.js

Running node-supervisor with
  program 'src/server.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node src/server.js'
Watching directory '/root/api-whatsapp-dev' for changes.
Press rs for restarting the process.
internal/modules/cjs/loader.js:329
      throw err;
      ^

Error: Cannot find module '/root/api-whatsapp-dev/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/root/api-whatsapp-dev/src/api/class/instance.js:7:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/root/api-whatsapp-dev/node_modules/@adiwajshing/baileys/package.json',
  requestPath: '@adiwajshing/baileys'
}
Program node src/server.js exited with code 1

Starting child process with 'node src/server.js'
internal/modules/cjs/loader.js:329
      throw err;
      ^

Error: Cannot find module '/root/api-whatsapp-dev/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/root/api-whatsapp-dev/src/api/class/instance.js:7:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/root/api-whatsapp-dev/node_modules/@adiwajshing/baileys/package.json',
  requestPath: '@adiwajshing/baileys'
}
Program node src/server.js exited with code 1

**Comment by salman0ansari** [comment]
i dont give support of edge version
