### ISSUE TITLE
npm run start error

### ISSUE THREAD

**Issue by vaccarieli** [salman0ansari/whatsapp-api-nodejs#47]
hi i have already jnstalled evrrything but it shows me this error aftr running npm run start

''0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
1 info using npm@7.5.2
2 info using node@v12.22.5
3 timing config:load:defaults Completed in 3ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 4ms
5 timing config:load:builtin Completed in 4ms
6 timing config:load:cli Completed in 3ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/vaccarieli/whatsapp-api-nodejs/.npmrc Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/home/vaccarieli/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 17ms
19 verbose npm-session 6e65e15b4cb34ab5
20 timing npm:load Completed in 35ms
21 timing command:run-script Completed in 383ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:314:20)
22 verbose stack     at maybeClose (internal/child_process.js:1022:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
23 verbose pkgid whatsapp-api-nodejs@3.0.0
24 verbose cwd /home/vaccarieli/whatsapp-api-nodejs
25 verbose Linux 5.13.0-35-generic
26 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
27 verbose node v12.22.5
28 verbose npm  v7.5.2
29 error code 1
30 error path /home/vaccarieli/whatsapp-api-nodejs
31 error command failed
32 error command sh -c node src/server.js
33 verbose exit 1'''

**Comment by salman0ansari** [comment]
use `yarn`

**Comment by salman0ansari** [comment]
`npm install -g yarn`

**Comment by vaccarieli** [comment]
i did `sudo npm install -g yarn` but am gettin a syntax error now:

```  
await WhatsAppInstances[req.query.key].instance?.sock?.logout()         
                                                        ^                       
                                                                                
SyntaxError: Unexpected token '.'                                               
    at wrapSafe (internal/modules/cjs/loader.js:915:16)                         
    at Module._compile (internal/modules/cjs/loader.js:963:27)                  
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)   
    at Module.load (internal/modules/cjs/loader.js:863:32)                      
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)            
    at Module.require (internal/modules/cjs/loader.js:887:19)                   
    at require (internal/modules/cjs/helpers.js:74:18)                          
    at Object.<anonymous> (/home/vaccarieli/whatsapp-api-nodejs/src/api/routes/i
nstance.route.js:2:20)                                                          
    at Module._compile (internal/modules/cjs/loader.js:999:30)                  
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)   
error Command failed with exit code 1.                                          
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
```

**Comment by vaccarieli** [comment]
it ran after installing latest npm version

`curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -`
`sudo apt-get install -y nodejs`

**Comment by vaccarieli** [comment]
@salman0ansari All is working, except idk how to scan the code i just get an html response, that does not seem to have valid qrcode or i guess dk how to read it, any hints? 

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>WhatsApp QrCode</title>
    <style>
        div {
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <h1> Scan Code Below Using WhatsApp App<h1>
            <div class="container">
                <img src="" alt="" id="qrcode_box" />
            </div>
</body>

```

**Comment by salman0ansari** [comment]
make get request from browser

**Comment by vaccarieli** [comment]
I am running the server on my ubuntu server (headless machine), and trying to pull up the browser request get on my windows laptop machine, do I have to run the server on the same machine that am making the requests from, or how can I do it?

**Comment by vaccarieli** [comment]
the qrcode is not working, when I try to scan it it says that it is invalid "Please scan again" and i try again but nothing seems to work :( @salman0ansari
