### ISSUE TITLE
No webhook post

### ISSUE THREAD

**Issue by xpsnetworks** [salman0ansari/whatsapp-api-nodejs#582]
Fresh and clean install on Ubuntu 20 AWS
4 GB RAM, 2 vCPUs, 80 GB SSD
Ubuntu
Oregon, Zone A (us-west-2a)

Send Messages => OK
Error occur only on docker-compose
After receive a message:

```
{"level":40,"time":"2023-03-10T23:53:36.998Z","pid":2434,"hostname":"X.X.XX.","stack":"Error: mutex start\n    at /opt/whatsapp-api/whatsapp-api-nodejs/node_m
odules/@adiwajshing/baileys/lib/Utils/make-mutex.js:15:31\n    at Object.mutex (/opt/whatsapp-api/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Utils/make-mute
x.js:35:15)\n    at handleMessage (/opt/whatsapp-api/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:451:29)\n    at execTask (/opt/whats
app-api/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:554:20)\n    at processNodeWithBuffer (/opt/whatsapp-api/whatsapp-api-nodejs/node
_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:551:15)\n    at WebSocket.<anonymous> (/opt/whatsapp-api/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/li
b/Socket/messages-recv.js:560:9)\n    at WebSocket.emit (events.js:400:28)\n    at /opt/whatsapp-api/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/socke
t.js:222:35\n    at Object.decodeFrame (/opt/whatsapp-api/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMess
ageRecieved (/opt/whatsapp-api/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)","waitOver":true,"msg":"possible mutex deadlock"}
```

**Comment by salman0ansari** [comment]
baileys error not related to API

**Comment by salman0ansari** [comment]
msg me on telegram @salman0ansari
